before_install:
  - chmod +x gradlew
  - mysql -e 'CREATE DATABASE trackdb;'
  
language: java
install: true
jdk: openjdk11
script:
  - ./gradlew build
  
addons:
  mariadb: '10.0'
  
services:
  - mariadb
